config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'welcome#index'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get '/register', to: 'users#new', as: 'register'
  post '/register', to: 'users#create'
  get '/dashboard', to: 'users#show'

  get '/discover', to: 'search#index'

  resources :questions do
    resources :answers, only: [:update]
  end

  resources :quizzes do
    resources :questions, only: [:new, :create, :update, :destroy]
  end

  resources :assessments, only: [:show, :create, :update]
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assessment.rb
class Assessment < ApplicationRecord
  belongs_to :quiz
  belongs_to :user
  has_many :questions, through: :quiz
  has_many :answers, through: :quiz

  enum status: {'in-progress': 0, completed: 1, cancelled: 2}

  def finish_assessment
    time = self.finishing_time.strftime('%s').to_i - self.starting_time.strftime('%s').to_i
    self.update(completed_time: time)
  end

  def percent_correct
    (self.score / self.number_of_questions) * 100
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :quiz
  has_one :answer, dependent: :destroy

  def question_answers
    if self.quiz.answers.length < 4
      short_quiz_answers
    elsif self.quiz.answers.length >= 4
      quiz_answers = self.quiz.answers.sample(3)

      if quiz_answers.include?(self.answer)
        question_answers
      elsif quiz_answers.uniq.length != 3
        question_answers
      elsif quiz_answers.uniq.length == 3 && !quiz_answers.include?(self.answer)
        quiz_answers << self.answer
        return quiz_answers.shuffle
      end
    end 
  end

  def short_quiz_answers
    self.quiz.answers.shuffle
  end
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :user
  has_many :questions, dependent: :destroy
  has_many :assessments, dependent: :destroy
  has_many :answers, through: :questions

  def user_assessments
    self.assessments.where(user_id: self.user.id) || []
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :quizzes
  has_many :assessments

  validates :email, presence: true, uniqueness: true, format: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  validates :password, presence: true
  validates :password, confirmation: { case_sensitive: true }

  has_secure_password
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def update
    answer = Answer.update(params[:id], answer_params)
    quiz = answer.question.quiz

    redirect_to "/quizzes/#{quiz.id}/questions/new"
  end

  private

  def answer_params
    params.permit(:answer, :question_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/assessments_controller.rb
class AssessmentsController < ApplicationController
  def show
    @assessment = Assessment.find(params[:id])
    @question = @assessment.questions[params[:question].to_i]
    @question_num = params[:question].to_i + 1
  end

  def create
    quiz = Quiz.find(params[:quiz_id])
    assessment = Assessment.create(score: 0, number_of_questions: quiz.questions.count, starting_time: Time.now, quiz: quiz, user_id: params[:user_id])

    redirect_to "/assessments/#{assessment.id}?question=0"
  end

  def update
    assessment = Assessment.find(params[:id])

    if params[:answer] == 'correct'
      assessment.update(score: assessment.score += 1)
    end

    if params[:assessment]
      assessment.update(finishing_time: Time.now)
      assessment.finish_assessment

      flash[:success] = "You Scored #{assessment.score} out of #{assessment.number_of_questions} in #{assessment.completed_time} seconds"
      redirect_to '/dashboard'
    else
      redirect_to "/assessments/#{assessment.id}?question=#{(params[:question].to_i + 1)}"
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new
    @quiz = Quiz.find(params[:quiz_id])
    if edit_params_and_question_present?
      @question = Question.find(params[:question_id])
    elsif edit_params_and_answer_present?
      @answer = Answer.find(params[:answer_id])
    end
  end

  def create
    quiz = Quiz.find(params[:quiz_id])
    question = quiz.questions.create(questions_params)
    Answer.create(answer: params[:answer], question: question)

    redirect_to "/quizzes/#{quiz.id}/questions/new"
  end

  def update
    Question.update(params[:id], questions_params)

    redirect_to "/quizzes/#{params[:quiz_id]}/questions/new"
  end

  def destroy
    question = Question.find(params[:id])
    question.destroy

    redirect_to "/quizzes/#{params[:quiz_id]}/questions/new"
  end

  private

  def questions_params
    params.permit(:question, :quiz_id)
  end

  def edit_params_and_question_present?
    params[:edit] && params[:question_id]
  end

  def edit_params_and_answer_present?
    params[:edit] && params[:answer_id]
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  def new
  end

  def edit
    @quiz = Quiz.find(params[:id])
  end

  def show
    @quiz = Quiz.find(params[:id])
  end

  def create
    quiz = Quiz.create(name: params[:name], subject: params[:subject], description: params[:description], user: current_user)

    redirect_to new_quiz_question_path(quiz.id)
  end

  def update
    quiz = Quiz.update(params[:id], quiz_params)

    redirect_to "/quizzes/#{quiz.id}"
  end

  def destroy
    quiz = Quiz.find(params[:id])
    quiz.destroy

    redirect_to '/dashboard'
  end

  private

  def quiz_params
    params.permit(:name, :subject, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:email])
    if !user.nil? && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome, #{user.email}!"
      redirect_to '/dashboard'
    else
      flash[:error] = 'Invalid Email or Password'
      redirect_to '/'
    end
  end

  def destroy
    session[:user_id] = nil

    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def new
  end

  def create
    user = User.create(user_params)
    if user.save
      session[:user_id] = user.id
      flash[:success] = "Welcome #{user.email}!"
      redirect_to '/dashboard'
    else
      flash[:error] = 'Sorry, your credentials are bad.'
      render :new
    end
  end

  private

  def user_params
    params.permit(:email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_edit.html.erb
<%= form_with url: "/questions/#{question.id}/answers/#{question.answer.id}", method: :patch, local: true do |f| %>
  <%= f.text_field :answer, value: question.answer.answer %>
  <%= f.submit 'Submit Answer', class: 'btn btn-success' %>
<% end %>

app/views/assessments/show.html.erb
<h3><%= @question.question %></h3> <h4>Question <%= @question_num %> of <%= @assessment.number_of_questions %></h4>

<% @question.question_answers.each do |answer| %>
<% if @question == @assessment.questions.last %>
<div id="answer-<%= answer.id %>">
  <% if answer == @question.answer %>
    <%= answer.answer %>
    <%= button_to 'Select Results', "/assessments/#{@assessment.id}", params: { answer: :correct, question_id: @question.id, answer_id: answer.id, assessment: :completed }, method: :patch %>
  <% elsif answer != @question.answer %>
    <%= answer.answer %>
    <%= button_to 'Select Answer', "/assessments/#{@assessment.id}", params: { answer: :wrong, question_id: @question.id, answer_id: answer.id, assessment: :completed  }, method: :patch %>
  <% end %>
<% else %>
<div id="answer-<%= answer.id %>">
  <% if answer == @question.answer %>
    <%= answer.answer %>
    <%= button_to 'Select Answer', "/assessments/#{@assessment.id}", params: { answer: :correct, question_id: @question.id, answer_id: answer.id, question: (@question_num - 1) }, method: :patch %>
  <% elsif answer != @question.answer %>
    <%= answer.answer %>
    <%= button_to 'Select Answer', "/assessments/#{@assessment.id}", params: { answer: :wrong, question_id: @question.id, answer_id: answer.id, question: (@question_num - 1) }, method: :patch %>
  <% end %>
  </div>
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if session[:user_id] || current_user %>
        <li class="nav-item">
          <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Discover Quizzes", discover_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Logout", logout_path, class: "nav-link" %>
        </li>
        <% else %>
        <li class="nav-item">
            <%= link_to 'Sign Up', register_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Log In', login_path, class: "nav-link" %>
        </li>
        <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudyAide</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <% flash.each do |type, msg| %>
    <div class="alert alert-warning" role="alert">
      <%= content_tag :div, msg, class: type %>
    </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/questions/_edit.html.erb
<%= form_with url: "/quizzes/#{@quiz.id}/questions/#{question.id}", method: :patch, local: true do |f| %>
  <%= f.text_field :question, value: question.question %>
  <%= f.submit 'Submit Question', class: 'btn btn-success' %>
<% end %>

app/views/questions/new.html.erb
<h3>Submit a Question the Answer for <%= @quiz.name %></h3>
<%= form_with url: "/quizzes/#{@quiz.id}/questions", method: :post, local: true do |f| %>
  <%= f.label :question, class: "form-control" %>
  <%= f.text_field :question, class: "form-control" %>
  <%= f.label :answer, class: "form-control" %>
  <%= f.text_field :answer, placeholder: 'Answer to Question', class: "form-control" %>
  <%= f.submit 'Submit', class: "btn btn-primary" %>
<% end %>

<% if !@quiz.questions.empty? %>
  <h4>Current Quiz Questions</h4>

  <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Question</th>
      <th scope="col">Answer</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <% @quiz.questions.each do |question| %>
   <div id="question-<%= question.id %>">
  <tbody>
    <tr class="table-light">
    <% if @question && @question.question == question.question %>

      <th scope="row"><%= @quiz.questions.index(question) + 1 %></th>
      <td><%= render partial: 'questions/edit', locals: { question: question } %></td>
      <td><%= question.answer.answer %></td>
      <td><%= button_to 'Edit Answer', "/quizzes/#{@quiz.id}/questions/new", method: :get, params: { edit: true, answer_id: question.answer.id}, class: 'btn btn-warning' %></td>
      <td><%= button_to 'Delete Question', "/quizzes/#{@quiz.id}/questions/#{question.id}", method: :delete, class: 'btn btn-danger' %>/td>

    <% elsif @answer && @answer.answer == question.answer.answer  %>

      <th scope="row"><%= @quiz.questions.index(question) + 1 %></th>
      <td><%= question.question %></td>
      <td><%= render partial: 'answers/edit', locals: { answer: @answer, question: question } %></td>
      <td><%= button_to 'Edit Question', "/quizzes/#{@quiz.id}/questions/new", method: :get, params: { edit: true, question_id: question.id}, class: 'btn btn-warning' %></td>
      <td><%= button_to 'Delete Question', "/quizzes/#{@quiz.id}/questions/#{question.id}", method: :delete, class: 'btn btn-danger' %></td>

    <% else %>
      <th scope="row"><%= @quiz.questions.index(question) + 1 %></th>
      <td><%= question.question %></td>
      <td><%= question.answer.answer %></td>
      <td><%= button_to 'Edit Question', "/quizzes/#{@quiz.id}/questions/new", method: :get, params: { edit: true, question_id: question.id}, class: 'btn btn-warning' %><br>
      <%= button_to 'Edit Answer', "/quizzes/#{@quiz.id}/questions/new", method: :get, params: { edit: true, answer_id: question.answer.id}, class: 'btn btn-warning' %></td>
      <td><%= button_to 'Delete Question', "/quizzes/#{@quiz.id}/questions/#{question.id}", method: :delete, class: 'btn btn-danger' %></td>
    </tr>
  </tbody>
    </div>
    <% end %>
  <% end %>
</table>
  <%= button_to 'Finish Question Submissions' %>
<% end %>

app/views/quizzes/edit.html.erb
<h3>Create A New Quiz</h3>
<%= form_with url: "/quizzes/#{@quiz.id}", method: :patch, local: true do |f| %>
  <%= f.label :name, class: "form-control" %>
  <%= f.text_field :name, value: @quiz.name, class: "form-control" %>
  <%= f.label :subject, class: "form-control" %>
  <%= f.text_field :subject, value: @quiz.subject, class: "form-control" %>
  <%= f.label :description, class: "form-control" %>
  <%= f.text_field :description, value: @quiz.description, class: "form-control" %>
  <%= f.submit 'Submit' %>
<% end %>

app/views/quizzes/new.html.erb
<h3>Create A New Quiz</h3>
<%= form_with url: '/quizzes', method: :post, local: true do |f| %>
  <%= f.label :name, class: "form-control" %>
  <%= f.text_field :name, class: "form-control" %>
  <%= f.label :subject, class: "form-control" %>
  <%= f.text_field :subject, class: "form-control" %>
  <%= f.label :description, class: "form-control" %>
  <%= f.text_field :description, class: "form-control" %>
  <%= f.submit 'Create Quiz' %>
<% end %>

app/views/quizzes/show.html.erb
<h3><%= @quiz.name %> Page</h3>
<p><%= @quiz.subject %></p>
<p><%= @quiz.description %></p>
<p>Number of Questions: <%= @quiz.questions.count %></p>

<%= button_to "Take Quiz", "/assessments", params: { quiz_id: @quiz.id, user_id: current_user.id }, method: :post, class: 'btn btn-success' %>
<%= button_to 'FlashCards', "", method: :get %>
<%= button_to 'Edit Quiz', "/quizzes/#{@quiz.id}/edit", method: :get %>
<%= button_to 'Delete Quiz', "/quizzes/#{@quiz.id}", method: :delete %>

app/views/users/new.html.erb
<h3>Welcome to Study Aide</h3>
    <%= form_with url: '/register', method: :post, local: true do |f| %>
    <%= f.label :email, class: "form-control" %>
    <%= f.text_field :email, class: "form-control" %>
    <%= f.label :password, class: "form-control" %>
    <%= f.password_field :password, class: "form-control" %>
    <%= f.label :password_confirmation, class: "form-control" %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
    <%= f.submit 'Submit' %>
  <% end %>

app/views/users/show.html.erb
<% if current_user %>
<h3>Welcome <%= current_user.email %></h3>
  <% if current_user.quizzes.empty? %>
    <p>You have no Quizzes yet</p>
    <%= button_to 'Create a New Quiz', '/quizzes/new', method: :get %>
  <% else %>

    <% current_user.quizzes.each do |quiz| %>
      <div id="quiz-<%= quiz.id %>">
        <div class="card" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title"><%= quiz.name %></h5>
            <h6 class="card-subtitle mb-2 text-muted"><%= quiz.subject %></h6>
            <p class="card-text"><%= quiz.description %></p>
            <p class="card-text"><%= button_to 'Visit Quiz Page', "/quizzes/#{quiz.id}", method: :get %></p>
            <% if !quiz.user_assessments.empty? %>
              <% quiz.user_assessments.each do |assessment| %>
                <div id="assessment-<%= assessment.id %>">
                    <p class="card-text">Assessment: <%= assessment.percent_correct.round(1) %>% taken on <%= assessment.starting_time.strftime('%a %b %e, %Y') %></p>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <br>
    <% end %>

    <%= button_to 'Create a New Quiz', '/quizzes/new', method: :get %>

  <% end %>

<% else %>
  <h3>You are Not Logged in!</h3>
  <%= button_to 'Log in Here', '/', method: :get %>
  <%= button_to 'Register an Account', '/register', method: :get %>
<% end %>

app/views/welcome/index.html.erb
<br>
<figure class="text-center">
  <blockquote class="blockquote">
    <h6 class="display-2">Welcome to Study Aide</h6>
  </blockquote>
  </figure>
<br>
    <%= form_with url: '/login', method: :post, local: true do |f| %>
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control", id: 'password' %>
    <br>
    <%= f.submit 'Login', class: 'btn btn-primary' %>
  <% end %>

<br>
  <%= button_to 'New to Study Aide? Register Here', register_path, method: :get %>